source 'https://github.com/CocoaPods/Specs.git'
#source 'https://gitee.com/mirrors/CocoaPods-Specs.git'
platform :ios,’10.0’  
target "DarkMode" do
  
pod 'GPUImage'
#pod 'MLeaksFinder'
pod 'MBProgressHUD'
pod 'Masonry'
pod 'YYImage'
pod 'YYWebImage'
pod 'YYModel'
pod 'YYModel'
pod 'MJRefresh'
end
